### ISSUE TITLE
On registration, a networks needs to be created for the user

### ISSUE THREAD

**Issue by eteubert** [podlove/radiator#79]
Currently the system requires a network to exist for a user, so we need to create a network on user registration, otherwise:

![image (2)](https://user-images.githubusercontent.com/235918/58432792-7b24f900-80b4-11e9-943c-aab85427b4a3.png)

**Comment by djschilling** [comment]
This bug is not reproducible.

When registering for a new account and the clicking on the email link one gets to this site:

<img width="1669" alt="Bildschirmfoto 2019-06-17 um 10 27 29" src="https://user-images.githubusercontent.com/3503166/59589609-9d75c980-90ea-11e9-8aaa-dd0e33890335.png">

I would suggest closing this issue.

**Comment by eteubert** [comment]
True, this was fixed a while ago. The code does not assume that there is a network any more.
